export const MOVEMENT_LIBRARY = [
  {
    id: "move_easy_walk",
    title: "Easy walk",
    durationMin: 10,
    intensity: 1,
    tags: ["light", "downshift", "eq:none"],
    contraTags: ["injury:knee", "injury:back"],
  },
  {
    id: "move_gentle_mobility",
    title: "Gentle mobility",
    durationMin: 8,
    intensity: 1,
    tags: ["light", "downshift", "eq:none"],
    contraTags: ["injury:back"],
  },
  {
    id: "move_stretch_flow",
    title: "Stretch flow",
    durationMin: 12,
    intensity: 1,
    tags: ["light", "downshift", "eq:none"],
    contraTags: ["injury:shoulder"],
  },
  {
    id: "move_light_strength",
    title: "Light strength circuit",
    durationMin: 15,
    intensity: 2,
    tags: ["light", "neutral", "eq:none"],
    contraTags: ["injury:shoulder", "injury:knee"],
  },
  {
    id: "move_band_activation",
    title: "Band activation",
    durationMin: 12,
    intensity: 2,
    tags: ["light", "neutral", "eq:bands"],
    contraTags: ["injury:shoulder"],
  },
  {
    id: "move_dumbbell_carry",
    title: "Dumbbell carry",
    durationMin: 12,
    intensity: 2,
    tags: ["neutral", "eq:dumbbells"],
    contraTags: ["injury:back", "injury:shoulder"],
  },
  {
    id: "move_brisk_walk",
    title: "Brisk walk",
    durationMin: 20,
    intensity: 3,
    tags: ["upswing", "eq:none"],
    contraTags: ["injury:knee", "injury:back"],
  },
  {
    id: "move_low_impact_cardio",
    title: "Low-impact cardio",
    durationMin: 18,
    intensity: 3,
    tags: ["upswing", "eq:none"],
    contraTags: ["injury:knee"],
  },
];
