export const RESET_LIBRARY_VERSION = "1";

export const RESET_LIBRARY = [
  {
    id: "reset_box_breathing",
    title: "Box breathing",
    durationSec: 240,
    seconds: 240,
    steps: [
      "Inhale through the nose for 4 counts",
      "Hold for 4 counts",
      "Exhale slowly for 4 counts",
      "Hold for 4 counts",
    ],
    tags: ["downshift", "breath", "steady", "demand:med"],
    contraTags: [],
  },
  {
    id: "reset_physiological_sigh",
    title: "Physiological sigh",
    durationSec: 180,
    seconds: 180,
    steps: [
      "Take a deep inhale",
      "Top off with a second small inhale",
      "Long, slow exhale",
      "Repeat for 6 to 8 rounds",
    ],
    tags: ["downshift", "breath", "quick", "demand:low"],
    contraTags: [],
  },
  {
    id: "reset_5_4_3_2_1",
    title: "5-4-3-2-1 grounding",
    durationSec: 240,
    seconds: 240,
    steps: [
      "Name 5 things you can see",
      "Name 4 things you can feel",
      "Name 3 things you can hear",
      "Name 2 things you can smell",
      "Name 1 thing you can taste",
    ],
    tags: ["grounding", "sensory", "demand:med"],
    contraTags: [],
  },
  {
    id: "reset_extended_exhale",
    title: "Extended exhale",
    durationSec: 180,
    seconds: 180,
    steps: [
      "Inhale for 4 counts",
      "Exhale for 6 to 8 counts",
      "Keep shoulders relaxed",
      "Repeat for 2 to 3 minutes",
    ],
    tags: ["downshift", "breath", "demand:low"],
    contraTags: [],
  },
  {
    id: "reset_body_scan",
    title: "Quick body scan",
    durationSec: 300,
    seconds: 300,
    steps: [
      "Notice your feet on the ground",
      "Scan up through legs and torso",
      "Relax jaw and shoulders",
      "Take 3 slow breaths",
    ],
    tags: ["downshift", "body", "demand:high"],
    contraTags: [],
  },
  {
    id: "reset_grounding_touch",
    title: "Grounding touch",
    durationSec: 150,
    seconds: 150,
    steps: [
      "Place one hand on chest and one on belly",
      "Breathe slowly and evenly",
      "Notice the rise and fall",
    ],
    tags: ["downshift", "body", "demand:low"],
    contraTags: [],
  },
  {
    id: "reset_horizon_gaze",
    title: "Horizon gaze",
    durationSec: 180,
    seconds: 180,
    steps: [
      "Look at a distant point",
      "Soften your gaze",
      "Take 6 slow breaths",
    ],
    tags: ["downshift", "sensory", "demand:low"],
    contraTags: [],
  },
  {
    id: "reset_gentle_neck_release",
    title: "Gentle neck release",
    durationSec: 180,
    seconds: 180,
    steps: [
      "Drop right ear toward right shoulder",
      "Hold for 3 breaths",
      "Switch sides",
    ],
    tags: ["downshift", "mobility", "demand:low"],
    contraTags: ["injury:neck"],
  },
  {
    id: "reset_micro_walk",
    title: "3-minute micro walk",
    durationSec: 180,
    seconds: 180,
    steps: [
      "Stand up and walk slowly",
      "Keep your breathing steady",
      "Shake out hands and shoulders",
    ],
    tags: ["downshift", "movement", "light", "demand:low"],
    contraTags: ["injury:knee", "injury:back"],
  },
  {
    id: "reset_stretch_break",
    title: "Gentle stretch break",
    durationSec: 240,
    seconds: 240,
    steps: [
      "Roll shoulders forward and back",
      "Stretch calves and hamstrings",
      "Take 3 slow breaths",
    ],
    tags: ["downshift", "movement", "light", "demand:med"],
    contraTags: ["injury:back"],
  },
  {
    id: "reset_counting_breaths",
    title: "Counting breaths",
    durationSec: 180,
    seconds: 180,
    steps: [
      "Inhale and count one",
      "Exhale and count two",
      "Continue up to ten",
      "Start again if you lose track",
    ],
    tags: ["downshift", "breath", "demand:low"],
    contraTags: [],
  },
  {
    id: "reset_quick_space",
    title: "Quick space check",
    durationSec: 120,
    seconds: 120,
    steps: [
      "Look around the room",
      "Name one safe detail",
      "Slow your exhale",
    ],
    tags: ["downshift", "short", "demand:low"],
    contraTags: [],
  },
];
