export const WORKOUT_LIBRARY_VERSION = "1";

export const WORKOUT_LIBRARY = [
  {
    id: "move_light_walk_10",
    title: "Light walk",
    minutes: 10,
    intensity: 1,
    equipmentTags: ["none"],
    effect: "downshift",
  },
  {
    id: "move_mobility_flow_8",
    title: "Mobility flow",
    minutes: 8,
    intensity: 1,
    equipmentTags: ["none"],
    effect: "downshift",
  },
  {
    id: "move_yoga_flow_15",
    title: "Gentle yoga flow",
    minutes: 15,
    intensity: 2,
    equipmentTags: ["none"],
    effect: "neutral",
  },
  {
    id: "move_bodyweight_strength_12",
    title: "Bodyweight strength",
    minutes: 12,
    intensity: 2,
    equipmentTags: ["none"],
    effect: "neutral",
  },
  {
    id: "move_brisk_walk_20",
    title: "Brisk walk",
    minutes: 20,
    intensity: 2,
    equipmentTags: ["none"],
    effect: "upswing",
  },
  {
    id: "move_light_intervals_18",
    title: "Light intervals",
    minutes: 18,
    intensity: 3,
    equipmentTags: ["none"],
    effect: "upswing",
  },
  {
    id: "move_dumbbell_circuit_15",
    title: "Dumbbell circuit",
    minutes: 15,
    intensity: 3,
    equipmentTags: ["dumbbells"],
    effect: "neutral",
  },
  {
    id: "move_band_strength_15",
    title: "Band strength",
    minutes: 15,
    intensity: 2,
    equipmentTags: ["bands"],
    effect: "neutral",
  },
  {
    id: "move_easy_cardio_25",
    title: "Easy cardio",
    minutes: 25,
    intensity: 3,
    equipmentTags: ["gym"],
    effect: "upswing",
  },
];
