export const nutritionSeed = [
  {
    id: "n_stabilize_plate",
    title: "Stabilize blood sugar plate",
    tags: ["stabilize", "food"],
    priorities: [
      "Protein at each meal (palm-sized).",
      "Fiber anchor (vegetables/beans/berries).",
      "Carbs paired with protein/fat; avoid sugar alone.",
      "Hydrate before caffeine.",
    ],
    contraindications: [],
    intensityCost: 1,
    minutes: 0,
  },
  {
    id: "n_downshift_evening",
    title: "Evening downshift nutrition",
    tags: ["downshift", "sleep", "food"],
    priorities: [
      "Earlier dinner if possible; lighter late meals.",
      "Limit alcohol tonight.",
      "If hungry late: protein + fiber (not sugar).",
    ],
    contraindications: ["avoid_late_meal"],
    intensityCost: 1,
    minutes: 0,
  },
  {
    id: "n_rebuild_training",
    title: "Rebuild support (training day)",
    tags: ["rebuild", "food"],
    priorities: [
      "Protein + carbs near training window if desired.",
      "Salt + hydration if active.",
      "Consistent meal timing to support rhythm.",
    ],
    contraindications: [],
    intensityCost: 2,
    minutes: 0,
  },
  {
    id: "n_caffeine_gate",
    title: "Morning caffeine gate",
    tags: ["stabilize", "caffeine"],
    priorities: [
      "Wait 60-90 minutes after waking before caffeine.",
      "Hydrate first (water + pinch of salt if desired).",
      "Stop caffeine 8-10 hours before bed.",
    ],
    contraindications: [],
    intensityCost: 0,
    minutes: 0,
  },
  {
    id: "n_caffeine_cutoff",
    title: "Caffeine cutoff reset",
    tags: ["downshift", "caffeine", "sleep"],
    priorities: [
      "No caffeine after noon today.",
      "Swap to water or herbal tea.",
      "Add a protein snack mid-afternoon.",
    ],
    contraindications: [],
    intensityCost: 0,
    minutes: 0,
  },
  {
    id: "n_half_caf_taper",
    title: "Half-caf taper",
    tags: ["stabilize", "caffeine"],
    priorities: [
      "Replace second cup with half-caf or green tea.",
      "Pair caffeine with food.",
      "Hydrate between cups.",
    ],
    contraindications: [],
    intensityCost: 0,
    minutes: 0,
  },
  {
    id: "n_low_appetite",
    title: "Low appetite support",
    tags: ["downshift", "stress", "food"],
    priorities: [
      "Small, frequent plates with protein.",
      "Use warm, easy-to-digest foods.",
      "Sip fluids steadily.",
    ],
    contraindications: [],
    intensityCost: 1,
    minutes: 0,
  },
  {
    id: "n_high_stress_simple",
    title: "High-stress simple meals",
    tags: ["downshift", "stress", "food"],
    priorities: [
      "Keep meals simple and repetitive today.",
      "Protein + fiber anchor at each meal.",
      "Avoid sugary snacks alone.",
    ],
    contraindications: [],
    intensityCost: 1,
    minutes: 0,
  },
  {
    id: "n_digestion_warm",
    title: "Digestion-friendly warm foods",
    tags: ["stabilize", "digestion", "food"],
    priorities: [
      "Prefer warm cooked meals.",
      "Add ginger or peppermint if helpful.",
      "Chew slowly and stop at comfortable fullness.",
    ],
    contraindications: [],
    intensityCost: 1,
    minutes: 0,
  },
  {
    id: "n_digestion_low_fodmap",
    title: "Gentle digestion plate",
    tags: ["stabilize", "digestion", "food"],
    priorities: [
      "Choose lower-FODMAP carbs if sensitive.",
      "Pair with lean protein.",
      "Limit raw crucifers today.",
    ],
    contraindications: [],
    intensityCost: 1,
    minutes: 0,
  },
  {
    id: "n_evening_light",
    title: "Light evening plate",
    tags: ["downshift", "sleep", "food"],
    priorities: [
      "Smaller dinner portion tonight.",
      "Prioritize protein + cooked veg.",
      "Finish eating 2-3 hours before bed.",
    ],
    contraindications: ["avoid_late_meal"],
    intensityCost: 1,
    minutes: 0,
  },
  {
    id: "n_sleep_fiber",
    title: "Sleep-supporting snack",
    tags: ["downshift", "sleep", "food"],
    priorities: [
      "If hungry late: protein + fiber snack.",
      "Avoid high-sugar desserts.",
      "Warm tea if desired.",
    ],
    contraindications: ["avoid_late_meal"],
    intensityCost: 0,
    minutes: 0,
  },
  {
    id: "n_rebuild_hydration",
    title: "Rebuild hydration + salt",
    tags: ["rebuild", "food"],
    priorities: [
      "Add electrolytes if training today.",
      "Salt meals to taste.",
      "Hydrate throughout the day.",
    ],
    contraindications: [],
    intensityCost: 1,
    minutes: 0,
  },
  {
    id: "n_protein_spread",
    title: "Protein spread",
    tags: ["stabilize", "food"],
    priorities: [
      "Distribute protein across meals.",
      "Aim for a palm-size each time.",
      "Add leucine-rich options if desired.",
    ],
    contraindications: [],
    intensityCost: 1,
    minutes: 0,
  },
  {
    id: "n_carbs_post_workout",
    title: "Post-workout carbs + protein",
    tags: ["rebuild", "food"],
    priorities: [
      "Eat within 1-2 hours of training.",
      "Pair carbs with protein.",
      "Hydrate and add salt.",
    ],
    contraindications: [],
    intensityCost: 2,
    minutes: 0,
  },
  {
    id: "n_breakfast_anchor",
    title: "Breakfast anchor",
    tags: ["stabilize", "food"],
    priorities: [
      "Protein + fiber at breakfast.",
      "Include healthy fat.",
      "Avoid sugary breakfast alone.",
    ],
    contraindications: [],
    intensityCost: 1,
    minutes: 0,
  },
  {
    id: "n_midday_balance",
    title: "Midday balance",
    tags: ["stabilize", "food"],
    priorities: [
      "Balanced plate at lunch.",
      "Walk 5 minutes after eating if possible.",
      "Hydrate with water.",
    ],
    contraindications: [],
    intensityCost: 1,
    minutes: 0,
  },
  {
    id: "n_stress_cravings",
    title: "Stress-craving buffer",
    tags: ["downshift", "stress", "food"],
    priorities: [
      "Add protein at snack time.",
      "Pair carbs with fat/fiber.",
      "Pause 60 seconds before second servings.",
    ],
    contraindications: [],
    intensityCost: 1,
    minutes: 0,
  },
  {
    id: "n_low_energy_simple",
    title: "Low-energy simple prep",
    tags: ["stabilize", "food"],
    priorities: [
      "Use simple, repeatable meals.",
      "Choose ready-to-eat protein.",
      "Add a pre-cut veg or fruit.",
    ],
    contraindications: [],
    intensityCost: 0,
    minutes: 0,
  },
  {
    id: "n_sleep_calm_routine",
    title: "Evening calm routine",
    tags: ["downshift", "sleep"],
    priorities: [
      "Finish eating earlier if possible.",
      "Warm shower or tea 1 hour before bed.",
      "Avoid spicy meals tonight.",
    ],
    contraindications: ["avoid_late_meal"],
    intensityCost: 0,
    minutes: 0,
  },
  {
    id: "n_rebuild_consistency",
    title: "Rebuild rhythm consistency",
    tags: ["rebuild", "food"],
    priorities: [
      "Keep meals at consistent times.",
      "Include protein at each meal.",
      "Hydrate and add salt if active.",
    ],
    contraindications: [],
    intensityCost: 1,
    minutes: 0,
  },
];
