export const resetsSeed = [
  {
    id: "r_breath_2",
    title: "2-min long-exhale breathing",
    minutes: 2,
    tags: ["downshift", "breath", "short"],
    steps: ["Inhale 4s", "Exhale 6s", "Repeat for 2 minutes"],
    contraindications: ["avoid_if_dizzy"],
    intensityCost: 0,
    noveltyGroup: "breath_long_exhale_short",
    priority: 5,
  },
  {
    id: "r_breath_3",
    title: "3-min long-exhale breathing",
    minutes: 3,
    tags: ["downshift", "breath", "short"],
    steps: ["Inhale 4s", "Exhale 6s", "Repeat for 3 minutes"],
    contraindications: ["avoid_if_dizzy"],
    intensityCost: 0,
    noveltyGroup: "breath_long_exhale_medium",
    priority: 5,
  },
  {
    id: "r_phys_sigh_2",
    title: "2-min physiological sigh",
    minutes: 2,
    tags: ["downshift", "breath", "short"],
    steps: ["Double inhale through nose", "Long exhale through mouth", "Repeat slowly"],
    contraindications: ["avoid_if_dizzy"],
    intensityCost: 0,
    noveltyGroup: "breath_phys_sigh",
    priority: 5,
  },
  {
    id: "r_box_3",
    title: "3-min box breathing",
    minutes: 3,
    tags: ["downshift", "breath", "short"],
    steps: ["Inhale 4s", "Hold 4s", "Exhale 4s", "Hold 4s"],
    contraindications: ["avoid_if_dizzy"],
    intensityCost: 0,
    noveltyGroup: "breath_box",
    priority: 4,
  },
  {
    id: "r_box_5",
    title: "5-min box breathing",
    minutes: 5,
    tags: ["downshift", "breath", "long"],
    steps: ["Inhale 4s", "Hold 4s", "Exhale 4s", "Hold 4s"],
    contraindications: ["avoid_if_dizzy"],
    intensityCost: 0,
    noveltyGroup: "breath_box_long",
    priority: 3,
  },
  {
    id: "r_name_it_3",
    title: "3-min name-and-frame",
    minutes: 3,
    tags: ["stabilize", "short"],
    steps: ["Write: what is happening (1 sentence)", "Write: next action (1 sentence)", "Do it"],
    contraindications: [],
    intensityCost: 1,
    noveltyGroup: "name_and_frame",
    priority: 4,
  },
  {
    id: "r_body_scan_5",
    title: "5-min body scan",
    minutes: 5,
    tags: ["sleep", "downshift", "long"],
    steps: ["Slow attention from head to toes", "Relax jaw/shoulders", "Long exhales"],
    contraindications: [],
    intensityCost: 0,
    noveltyGroup: "body_scan",
    priority: 4,
  },
  {
    id: "r_eyes_2",
    title: "2-min eyes + neck release",
    minutes: 2,
    tags: ["downshift", "short"],
    steps: ["Look left/right slowly", "Gentle neck circles", "Long exhales"],
    contraindications: [],
    intensityCost: 0,
    noveltyGroup: "eyes_neck_release",
    priority: 3,
  },
  {
    id: "r_eyes_5",
    title: "5-min eyes + neck reset",
    minutes: 5,
    tags: ["downshift", "long"],
    steps: ["Eye tracking slow circles", "Neck side stretch", "Finish with slow exhales"],
    contraindications: [],
    intensityCost: 0,
    noveltyGroup: "eyes_neck_release_long",
    priority: 3,
  },
  {
    id: "r_ground_2",
    title: "2-min grounding",
    minutes: 2,
    tags: ["downshift", "short"],
    steps: ["Name 5 things you see", "4 things you feel", "3 slow exhales"],
    contraindications: [],
    intensityCost: 0,
    noveltyGroup: "grounding",
    priority: 3,
  },
  {
    id: "r_shake_3",
    title: "3-min shake + breathe",
    minutes: 3,
    tags: ["stabilize", "short"],
    steps: ["Shake arms/legs gently", "Breathe long exhales"],
    contraindications: [],
    intensityCost: 1,
    noveltyGroup: "shake_breathe",
    priority: 3,
  },
  {
    id: "r_walk_5",
    title: "5-min gentle walk",
    minutes: 5,
    tags: ["stabilize", "long"],
    steps: ["Walk slowly", "Notice your feet and breath"],
    contraindications: [],
    intensityCost: 1,
    noveltyGroup: "reset_walk",
    priority: 3,
  },
  {
    id: "r_journal_5",
    title: "5-min brain dump",
    minutes: 5,
    tags: ["stabilize", "long"],
    steps: ["Write everything on your mind", "Circle the next action"],
    contraindications: [],
    intensityCost: 1,
    noveltyGroup: "brain_dump",
    priority: 3,
  },
  {
    id: "r_nasal_3",
    title: "3-min nasal breathing",
    minutes: 3,
    tags: ["downshift", "breath", "short"],
    steps: ["Close mouth", "Slow inhale/exhale", "Relax shoulders"],
    contraindications: ["avoid_if_congested"],
    intensityCost: 0,
    noveltyGroup: "breath_nasal",
    priority: 4,
  },
  {
    id: "r_legs_up_5",
    title: "5-min legs up the wall",
    minutes: 5,
    tags: ["sleep", "downshift", "long"],
    steps: ["Lie down with legs elevated", "Slow exhales"],
    contraindications: ["avoid_if_back_pain"],
    intensityCost: 0,
    noveltyGroup: "legs_up_wall",
    priority: 4,
  },
  {
    id: "r_progressive_5",
    title: "5-min progressive relax",
    minutes: 5,
    tags: ["sleep", "downshift", "long"],
    steps: ["Tense then relax each muscle group", "Slow breathing"],
    contraindications: [],
    intensityCost: 1,
    noveltyGroup: "progressive_relax",
    priority: 3,
  },
  {
    id: "r_breath_4",
    title: "4-min long exhale",
    minutes: 4,
    tags: ["downshift", "breath", "long"],
    steps: ["Inhale 4s", "Exhale 7s", "Repeat"],
    contraindications: ["avoid_if_dizzy"],
    intensityCost: 0,
    noveltyGroup: "breath_long_exhale_long",
    priority: 3,
  },
  {
    id: "r_stretch_5",
    title: "5-min shoulder release",
    minutes: 5,
    tags: ["stabilize", "long"],
    steps: ["Cross-body stretch", "Doorway chest stretch", "Long exhales"],
    contraindications: [],
    intensityCost: 1,
    noveltyGroup: "shoulder_release",
    priority: 3,
  },
  {
    id: "r_warm_face_2",
    title: "2-min warm face wash",
    minutes: 2,
    tags: ["downshift", "short"],
    steps: ["Warm water on face", "Slow breathing", "Relax jaw"],
    contraindications: [],
    intensityCost: 0,
    noveltyGroup: "warm_face",
    priority: 2,
  },
  {
    id: "r_countdown_3",
    title: "3-min countdown breath",
    minutes: 3,
    tags: ["downshift", "breath", "short"],
    steps: ["Inhale 4s", "Exhale 8s", "Count down 10 to 1"],
    contraindications: ["avoid_if_dizzy"],
    intensityCost: 0,
    noveltyGroup: "breath_countdown",
    priority: 3,
  },
];
