export const workoutsSeed = [
  {
    id: "w_walk_10",
    title: "10-min downshift walk",
    minutes: 10,
    intensity: "low",
    modality: "walk",
    tags: ["downshift", "short", "zone2"],
    steps: ["Walk easy. Nasal breathing if possible.", "End with 60s slow exhale breathing."],
  },
  {
    id: "w_mob_8",
    title: "8-min mobility reset",
    minutes: 8,
    intensity: "low",
    modality: "mobility",
    tags: ["downshift", "short", "mobility"],
    steps: ["2 min neck/shoulders", "3 min hips", "3 min spine + deep breathing"],
  },
  {
    id: "w_strength_20",
    title: "20-min gentle strength",
    minutes: 20,
    intensity: "moderate",
    modality: "strength",
    tags: ["stabilize", "medium", "strength"],
    steps: ["Circuit x3: squat pattern, push, pull (easy effort)", "Stop 2 reps before failure"],
  },
  {
    id: "w_zone2_30",
    title: "30-min zone-2 rebuild",
    minutes: 30,
    intensity: "moderate",
    modality: "zone2",
    tags: ["rebuild", "long", "zone2"],
    steps: ["Sustainable pace. You can speak in full sentences.", "Cooldown 3 minutes very easy."],
  },
  {
    id: "w_yoga_15",
    title: "15-min nervous system yoga",
    minutes: 15,
    intensity: "low",
    modality: "yoga",
    tags: ["downshift", "medium", "mobility", "breath"],
    steps: ["Slow flow + long exhales", "Finish: legs-up-the-wall 2 minutes"],
  },
];
