export const workoutsSeed = [
  // Downshift (6)
  {
    id: "w_walk_5",
    title: "5-min easy walk",
    minutes: 5,
    intensity: "low",
    modality: "walk",
    tags: ["downshift", "short", "zone2"],
    steps: ["Walk easy and slow.", "Nasal breathing if possible."],
    contraindications: [],
    intensityCost: 1,
    noveltyGroup: "walk_easy_short",
    priority: 5,
  },
  {
    id: "w_walk_10",
    title: "10-min downshift walk",
    minutes: 10,
    intensity: "low",
    modality: "walk",
    tags: ["downshift", "short", "zone2"],
    steps: ["Walk easy. Nasal breathing if possible.", "End with 60s slow exhale breathing."],
    contraindications: [],
    intensityCost: 2,
    noveltyGroup: "walk_easy_medium",
    priority: 4,
  },
  {
    id: "w_breathwalk_12",
    title: "12-min breath-led walk",
    minutes: 12,
    intensity: "low",
    modality: "walk",
    tags: ["downshift", "medium", "breath", "zone2"],
    steps: ["Inhale 3 steps, exhale 5 steps.", "Keep pace easy and smooth."],
    contraindications: ["avoid_if_dizzy"],
    intensityCost: 2,
    noveltyGroup: "walk_breath",
    priority: 4,
  },
  {
    id: "w_mob_8",
    title: "8-min mobility reset",
    minutes: 8,
    intensity: "low",
    modality: "mobility",
    tags: ["downshift", "short", "mobility"],
    steps: ["2 min neck/shoulders", "3 min hips", "3 min spine + deep breathing"],
    contraindications: [],
    intensityCost: 1,
    noveltyGroup: "mobility_reset",
    priority: 5,
  },
  {
    id: "w_stretch_10",
    title: "10-min floor stretch",
    minutes: 10,
    intensity: "low",
    modality: "mobility",
    tags: ["downshift", "short", "mobility"],
    steps: ["Slow hamstring + hip stretch", "Finish with long exhales"],
    contraindications: [],
    intensityCost: 1,
    noveltyGroup: "mobility_floor",
    priority: 3,
  },
  {
    id: "w_yoga_15",
    title: "15-min nervous system yoga",
    minutes: 15,
    intensity: "low",
    modality: "yoga",
    tags: ["downshift", "medium", "mobility", "breath"],
    steps: ["Slow flow + long exhales", "Finish: legs-up-the-wall 2 minutes"],
    contraindications: [],
    intensityCost: 2,
    noveltyGroup: "yoga_nervous",
    priority: 4,
  },

  // Stabilize (8)
  {
    id: "w_strength_15",
    title: "15-min gentle strength",
    minutes: 15,
    intensity: "moderate",
    modality: "strength",
    tags: ["stabilize", "short", "strength"],
    steps: ["Circuit x2: squat pattern, push, pull", "Stop 2 reps before failure"],
    contraindications: ["avoid_if_poor_sleep"],
    intensityCost: 4,
    minSleepQuality: 5,
    noveltyGroup: "strength_gentle_short",
    priority: 4,
  },
  {
    id: "w_strength_20",
    title: "20-min gentle strength",
    minutes: 20,
    intensity: "moderate",
    modality: "strength",
    tags: ["stabilize", "medium", "strength"],
    steps: ["Circuit x3: squat pattern, push, pull (easy effort)", "Stop 2 reps before failure"],
    contraindications: ["avoid_if_poor_sleep"],
    intensityCost: 5,
    minSleepQuality: 5,
    noveltyGroup: "strength_gentle",
    priority: 5,
  },
  {
    id: "w_zone2_20",
    title: "20-min zone-2 steady",
    minutes: 20,
    intensity: "moderate",
    modality: "zone2",
    tags: ["stabilize", "medium", "zone2"],
    steps: ["Sustainable pace. You can speak in full sentences.", "Cooldown 2 minutes very easy."],
    contraindications: [],
    intensityCost: 4,
    minSleepQuality: 4,
    noveltyGroup: "zone2_steady_short",
    priority: 4,
  },
  {
    id: "w_zone2_25",
    title: "25-min zone-2 base",
    minutes: 25,
    intensity: "moderate",
    modality: "zone2",
    tags: ["stabilize", "medium", "zone2"],
    steps: ["Steady pace. Keep breathing calm.", "Cooldown 3 minutes easy."],
    contraindications: [],
    intensityCost: 5,
    minSleepQuality: 5,
    noveltyGroup: "zone2_steady",
    priority: 4,
  },
  {
    id: "w_mob_core_18",
    title: "18-min mobility + core",
    minutes: 18,
    intensity: "moderate",
    modality: "mobility",
    tags: ["stabilize", "medium", "strength"],
    steps: ["Flow: hips, spine, shoulder circles", "Core: dead bug + side plank"],
    contraindications: ["avoid_if_low_back_pain"],
    intensityCost: 4,
    minSleepQuality: 4,
    noveltyGroup: "mobility_core",
    priority: 3,
  },
  {
    id: "w_brisk_15",
    title: "15-min brisk walk",
    minutes: 15,
    intensity: "moderate",
    modality: "walk",
    tags: ["stabilize", "short", "zone2"],
    steps: ["Walk briskly but stay conversational.", "Cooldown 1 minute easy."],
    contraindications: [],
    intensityCost: 3,
    minSleepQuality: 4,
    noveltyGroup: "walk_brisk",
    priority: 3,
  },
  {
    id: "w_stability_22",
    title: "22-min stability circuit",
    minutes: 22,
    intensity: "moderate",
    modality: "strength",
    tags: ["stabilize", "medium", "strength"],
    steps: ["Circuit x3: hinge, row, carry", "Keep effort 6/10"],
    contraindications: ["avoid_if_poor_sleep"],
    intensityCost: 5,
    minSleepQuality: 5,
    noveltyGroup: "strength_stability",
    priority: 4,
  },
  {
    id: "w_cycle_25",
    title: "25-min easy spin",
    minutes: 25,
    intensity: "moderate",
    modality: "zone2",
    tags: ["stabilize", "medium", "zone2"],
    steps: ["Easy cadence, low resistance.", "Finish with 2 min slow pedal."],
    contraindications: [],
    intensityCost: 4,
    minSleepQuality: 4,
    noveltyGroup: "zone2_cycle",
    priority: 3,
  },

  // Rebuild (6)
  {
    id: "w_zone2_30",
    title: "30-min zone-2 rebuild",
    minutes: 30,
    intensity: "moderate",
    modality: "zone2",
    tags: ["rebuild", "long", "zone2"],
    steps: ["Sustainable pace. You can speak in full sentences.", "Cooldown 3 minutes very easy."],
    contraindications: ["avoid_if_poor_sleep"],
    intensityCost: 6,
    minSleepQuality: 6,
    noveltyGroup: "zone2_rebuild_30",
    priority: 5,
  },
  {
    id: "w_zone2_40",
    title: "40-min zone-2 base",
    minutes: 40,
    intensity: "moderate",
    modality: "zone2",
    tags: ["rebuild", "long", "zone2"],
    steps: ["Keep effort steady and smooth.", "Cooldown 4 minutes easy."],
    contraindications: ["avoid_if_poor_sleep"],
    intensityCost: 7,
    minSleepQuality: 6,
    noveltyGroup: "zone2_rebuild_40",
    priority: 4,
  },
  {
    id: "w_strength_30",
    title: "30-min strength rebuild",
    minutes: 30,
    intensity: "moderate",
    modality: "strength",
    tags: ["rebuild", "long", "strength"],
    steps: ["Circuit x4: squat, push, pull", "Keep effort 7/10"],
    contraindications: ["avoid_if_poor_sleep"],
    intensityCost: 7,
    minSleepQuality: 6,
    noveltyGroup: "strength_rebuild_30",
    priority: 4,
  },
  {
    id: "w_strength_35",
    title: "35-min strength + core",
    minutes: 35,
    intensity: "moderate",
    modality: "strength",
    tags: ["rebuild", "long", "strength"],
    steps: ["Circuit x4: hinge, press, carry", "Finish with 6-min core"],
    contraindications: ["avoid_if_poor_sleep"],
    intensityCost: 8,
    minSleepQuality: 7,
    noveltyGroup: "strength_rebuild_35",
    priority: 3,
  },
  {
    id: "w_hike_45",
    title: "45-min steady hike",
    minutes: 45,
    intensity: "moderate",
    modality: "walk",
    tags: ["rebuild", "long", "zone2"],
    steps: ["Steady pace, nasal breathing if possible.", "Cooldown 5 minutes easy."],
    contraindications: ["avoid_if_poor_sleep"],
    intensityCost: 8,
    minSleepQuality: 6,
    noveltyGroup: "walk_hike",
    priority: 3,
  },
  {
    id: "w_mix_30",
    title: "30-min mixed endurance",
    minutes: 30,
    intensity: "moderate",
    modality: "zone2",
    tags: ["rebuild", "medium", "zone2"],
    steps: ["10 min easy + 15 min steady + 5 min easy", "Keep effort 6-7/10"],
    contraindications: ["avoid_if_poor_sleep"],
    intensityCost: 6,
    minSleepQuality: 6,
    noveltyGroup: "zone2_mix",
    priority: 4,
  },
];
